### ISSUE TITLE
这几天公众号的RSS是失效吗

### ISSUE THREAD

**Issue by JunQu** [ChanceYu/front-end-rss#1]
冒昧问一下，因为那几个公众号（前端早读课、前端之巅、前端大全）的文章这几天都没有更新，前面是每天更新的。顺便可以问问公众号RSS订阅的方式吗？
这几个订阅和我非常相近，谢谢你的分享。

**Comment by ChanceYu** [comment]
目前公众号使用的是即刻主题订阅，应该是挂了，回头看看怎么处理

**Comment by ChanceYu** [comment]
> 冒昧问一下，因为那几个公众号（前端早读课、前端之巅、前端大全）的文章这几天都没有更新，前面是每天更新的。顺便可以问问公众号RSS订阅的方式吗？
> 这几个订阅和我非常相近，谢谢你的分享。

公众号更新已经修复
