### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by JunQu** [ChanceYu/front-end-rss#2]
最近通过邮件提醒，我觉得这让我打开的次数又多了起来，但是，是不是频率频繁了点。因为在工作中，我只想在早上或者晚上看到一篇的合集，并不是很需要每次更新就提醒我，这样类似medium的每日推荐，过于频繁不得不迫使我取消他，希望能改进一下，谢谢。

**Comment by ChanceYu** [comment]
暂不打算支持

**Comment by laampui** [comment]
@ChanceYu  主站（https://front-end-rss.now.sh/）有开发 RSS 订阅功能的打算吗？
