### ISSUE TITLE
请教关于源码中的定时任务

### ISSUE THREAD

**Issue by ltyzzzxxx** [ChanceYu/front-end-rss#32]
请问一下作者的定时任务是部署到 vercel 上运行还是在单独的服务器上运行呢？

因为我发现需要用到 simpleGit 进行 push 操作，如果是 vercel 的话，如何配置 Github push 的权限呢？

求解答～感谢项目做出的贡献～

**Comment by ChanceYu** [comment]
> 

vercel 上要 push 的话可能要配置 github ssh 账号并执行 ssh-add 再去运行任务，没试过这个
