### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by vannvan** [ChanceYu/front-end-rss#34]
借用[@Liam](https://github.com/7kms)的一句话
> 当下前端技术圈总体比较浮躁, 各技术平台充斥着不少"标题党". 真正对于技术本身, 不能急于求成, 需要静下心来修炼.

使用`RSS`订阅作者这个仓库已经几个月了，但最近尤其觉得抓来的“劣质”内容多了些，这些“劣质”内容形如“今年这情况。。。多一个选择吧“，“被裁3个月，昨天刚上岸......“...内容基本上全是原作者“恰饭”的引流文章，我个人理解这些原作者需要创作动力需要恰饭，但是这些铺天盖地贩卖焦虑和恰饭的内容无疑会给众多读者长期传输焦虑，很反感这种现象。

仓库的介绍是

> 每天定时抓取最新前端技术文章，并推送到 GitHub 方便查看

目前“量”已经有了，“质”是否考虑提升一下？

因此如果作者没有这方面的需求的话，是否考虑将这部分内容过滤掉？

**Comment by ChanceYu** [comment]
> 

很好的建议，近期将考虑增加此过滤功能

**Comment by chokcoco** [comment]
偶然看到，建议剔除公众号非原创文章... 尴尬~

**Comment by ChanceYu** [comment]
已支持，感谢反馈

![image](https://github.com/ChanceYu/front-end-rss/assets/12869521/57f9e2de-b1ce-467d-8ec1-2ad60301f33d)
