### ISSUE TITLE
【播客自荐】web worker 前端技术播客

### ISSUE THREAD

**Issue by Otto-J** [ChanceYu/front-end-rss#40]
我想自荐一个中文音频播客节目，叫 [web worker](https://www.xiaoyuzhoufm.com/podcast/613753ef23c82a9a1ccfdf35)，有点特殊的是，内容以音频为主，文字为辅。目前持续更新三十多期了，rss 我提供如下 https://feed.xyzfm.space/rv449dl9kqka 

不清楚是否合适，如果不合适多有打扰，随时可以关闭

**Comment by ChanceYu** [comment]
音频博客也不错，比较适合参与性的话题讨论和头脑风暴，但此项目的 rss 收集更注重文字形式
