### ISSUE TITLE
应该过滤技术无关的内容

### ISSUE THREAD

**Issue by nanvon** [ChanceYu/front-end-rss#41]
举最近的几个例子：“开眼了！中国奇葩宿舍设计大赏"、“昨天去世，他们全都不在了”

这些完全和技术无关的内容应该被过滤掉。

**Comment by ChanceYu** [comment]
已支持，感谢反馈

![image](https://github.com/ChanceYu/front-end-rss/assets/12869521/57f9e2de-b1ce-467d-8ec1-2ad60301f33d)
