### ISSUE TITLE
【博客自荐】个人的前端技术博客

### ISSUE THREAD

**Issue by hughfenghen** [ChanceYu/front-end-rss#43]
关注 Web 前沿基础技术的应用（WebCodecs、OPFS、WASM 等等）、经验沉淀
目前日均约 300  PV，准备专注前端技术，更新前端原创文章、长期运营

博客首页：https://hughfenghen.github.io/
rss 链接：https://hughfenghen.github.io/rss.xml

**Comment by ChanceYu** [comment]
感谢提供，已添加 rss。你的 [WebAV](https://github.com/hughfenghen/WebAV/)  项目我之前也有关注，希望将来能有机会交流合作。开工第一天，新年快乐~

**Comment by hughfenghen** [comment]
@ChanceYu  哈哈，真巧；新年快乐～🎇
