### ISSUE TITLE
可以提供一下RSS的订阅连接吗

### ISSUE THREAD

**Issue by nihaojob** [ChanceYu/front-end-rss#6]

**Comment by FE-ng** [comment]
感谢您的认可 现在博客已经加上RSS链接了

https://droplets.vercel.app/atom.xml

秦少卫 ***@***.***> 于2021年7月8日周四 上午11:28写道：

**Comment by ChanceYu** [comment]
参考：data/rss.json

**Comment by nihaojob** [comment]
> 参考：data/rss.json

收到 感谢

**Comment by ChanceYu** [comment]
此功能已上线，Feed 订阅地址：https://fed.chanceyu.com/atom.xml
